const _data = {
    "zh-cn": {
        "com_loading_wait": "加载中...",
        "com_loading_title": "加载中",
        "com_import": "导入",
        "com_explore": "浏览",
        "com_ok": "确定",
        "com_update": "更新",
        "com_next": "下一步",
        "com_skip": "跳过",
        "com_continue": "继续",
        "com_export": "导出",
        "com_retry": "重试",
        "com_modify": "修改",
        "com_apply": "应用",
        "com_cancel": "取消",
        "com_complete": "完成",
        "com_tips": "提示",
        "com_add": "添加",
        "com_remove": "移除",
        "com_join": "加入",
        "com_quit": "退出",
        "com_download": "下载",
        "com_unknown": "未知",
        "com_loading": "加载中...",
        "com_empty": "暂时没有项目",
        "com_onlype": "此功能仅在 FlysoftPE 内可用，请切换到 FlysoftPE 下进行使用。",
        "ip_welcome": "欢迎使用 FlysoftPE 镜像导入向导",
        "ip_import": "正在导入 FlysoftPE",
        "ip_complete": "导入成功 FlysoftPE",
        "ip_formaterr": "此镜像可能不是一个有效的 FlysoftPE 镜像。",
        "wiz_welcome": "欢迎使用 FlysoftPE",
        "wiz_mode": "选择一个方案",
        "wiz_mode_ramos": "RAMOS",
        "wiz_mode_pe": "PE",
        "wiz_mode_description_ramos": "此方案适用于日常使用，拥有强大的娱乐功能。",
        "wiz_mode_description_pe": "此方案适用于维护电脑系统，拥有众多维护工具。",
        "wiz_device": "选择安装位置",
        "wiz_device_usb": "U 盘",
        "wiz_device_iso": "ISO 镜像",
        "wiz_install": "正在安装 FlysoftPE",
        "wiz_complete": "安装成功",
        "wiz_anyway": "硬盘上已经安装了 FlysoftPE，继续安装吗？",
        "wiz_planerr": "选中的方案不存在。",
        "wiz_fileerr": "资源文件丢失。",
        "wiz_isoerr": "写入 ISO 镜像时出现故障。",
        "wiz_usbtip": "请将 Ventoy 安装到 U 盘内，然后点击继续。",
        "hub_title": "FlysoftPE",
        "hub_notinstalled": "未检测到 FlysoftPE 启动盘！请先到主页制作一个新的启动盘。",
        "hub_menu_home": "主页",
        "hub_menu_install": "写入",
        "hub_menu_store": "商店",
        "hub_menu_settings": "设置",
        "hub_menu_drivers": "驱动",
        "hub_menu_docs": "文档",
        "hub_home_write_title": "安装 FlysoftPE",
        "hub_home_write_sub": "请制作一个新的启动盘或插入现有启动盘",
        "hub_home_write_btn": "立刻安装",
        "hub_home_update_title": "FlysoftPE 有新的版本",
        "hub_home_update_sub": "更新 FlysoftPE 以获得更好的体验",
        "hub_home_update_btn": "更新",
        "hub_home_updatehub_title": "FlysoftPE Hub 有新的版本",
        "hub_home_updatehub_sub": "请保持 FlysoftPE Hub 为最新版本",
        "hub_home_updatehub_btn": "更新",
        "hub_home_updateusb_title": "启动盘内的 FlysoftPE 需要更新",
        "hub_home_updateusb_sub": "更新启动盘内的 FlysoftPE 以获得更好的体验",
        "hub_home_updateusb_btn": "更新",
        "hub_home_offline_title": "你已经离线",
        "hub_home_offline_sub": "请连接到网络后重试",
        "hub_home_offline_btn": "重试",
        "hub_home_loading_title": "加载中...",
        "hub_home_loading_sub": "请稍后...",
        "hub_home_ok_title": "你已安装 FlysoftPE",
        "hub_home_ok_3rd_title": "你已安装 PE_NAME",
        "hub_home_ok_sub": "试试新插件 >>",
        "hub_home_ok_btn": "转到商店",
        "hub_home_no_title": "欢迎使用 FlysoftPE",
        "hub_home_no_sub": "要开始使用，请先下载资源文件",
        "hub_home_no_btn": "立刻下载",
        "hub_store_title": "FlysoftPE Store",
        "hub_store_author": "插件作者: ",
        "hub_store_time": "更新日期: ",
        "hub_store_success": "安装成功",
        "hub_store_reqerr": "请求失败",
        "hub_store_reqing": "拉取索引中",
        "hub_store_downloading": "正在从服务器下载...",
        "hub_store_extracting": "正在解压缩插件包...",
        "hub_store_adding": "正在向你的启动盘添加插件...",
        "hub_store_waiting": "等待启动盘插入...",
        "hub_store_remove": "正在移除插件 ",
        "hub_store_btn1": "主页",
        "hub_store_btn2": "库",
        "hub_store_btn3": "已安装",
        "hub_store_empty": "空空如也",
        "hub_set_title": "FlysoftPE 设置",
        "hub_set_wp": "壁纸",
        "hub_set_app": "样式",
        "hub_set_app_cmode": "颜色模式",
        "hub_set_app_cmode_theme": "默认",
        "hub_set_app_cmode_light": "亮色",
        "hub_set_app_cmode_dark": "暗色",
        "hub_set_app_taskbar": "任务栏样式",
        "hub_set_app_taskbar_edit": "编辑",
        "hub_set_app_taskbar_remove": "默认",
        "hub_set_disp": "显示",
        "hub_set_disp_bright": "亮度",
        "hub_set_disp_res": "分辨率",
        "hub_set_disp_res_def": "自动",
        "hub_set_disp_res_other": "自定义",
        "hub_set_sound": "声音",
        "hub_set_sound_vol": "默认音量",
        "hub_set_env": "环境",
        "hub_set_env_mode": "用户数据保存",
        "hub_set_env_mode_save": "保存到 U 盘内",
        "hub_set_env_mode_nosave": "不保存",
        "hub_set_insider": "Flysoft Insider",
        "hub_set_insider_join": "加入 Flysoft Insider 获取最新功能和特性，但是稳定性较差",
        "hub_set_insider_err": "请输入正确的内测码",
        "hub_drivers_title": "驱动管理",
        "hub_drivers_device": "驱动程序",
        "hub_drivers_part_amd": "AMD",
        "hub_drivers_part_nvidia": "英伟达",
        "hub_drivers_part_intel": "英特尔",
        "hub_drivers_part_ms": "微软",
        "hub_drivers_part_qualcomm": "高通",
        "hub_drivers_part_3dfx": "3DFX",
        "hub_drivers_part_ati": "ATI",
        "hub_drivers_part_google": "谷歌",
        "hub_drivers_part_apple": "苹果",
        "hub_drivers_part_lsi": "LSI",
        "hub_drivers_part_hp": "惠普",
        "hub_drivers_part_hw": "华为",
        "hub_drivers_type_1394": "1394",
        "hub_drivers_type_61883": "61883",
        "hub_drivers_type_androidusbdeviceclass": "安卓手机",
        "hub_drivers_type_audioprocessingobject": "音频处理",
        "hub_drivers_type_avc": "视频处理",
        "hub_drivers_type_barcodescanner": "二维码扫描",
        "hub_drivers_type_battery": "电池",
        "hub_drivers_type_biometric": "生物识别",
        "hub_drivers_type_bluetooth": "蓝牙",
        "hub_drivers_type_camera": "相机",
        "hub_drivers_type_cashdrawer": "现金柜子",
        "hub_drivers_type_cdrom": "光驱",
        "hub_drivers_type_computeaccelerator": "计算加速器",
        "hub_drivers_type_computer": "计算机",
        "hub_drivers_type_diskdrive": "磁盘",
        "hub_drivers_type_display": "显卡",
        "hub_drivers_type_dot4": "Dot4",
        "hub_drivers_type_dot4print": "Dot4 打印",
        "hub_drivers_type_extension": "扩展",
        "hub_drivers_type_fdc": "盘控制器",
        "hub_drivers_type_firmware": "固件",
        "hub_drivers_type_floppydisk": "软盘",
        "hub_drivers_type_image": "图像设备",
        "hub_drivers_type_keyboard": "键盘",
        "hub_drivers_type_fdc": "盘控制器",
        "hub_drivers_type_modem": "调制解调器",
        "hub_drivers_type_monitor": "监视器",
        "hub_drivers_type_media": "声音",
        "hub_drivers_type_mouse": "鼠标",
        "hub_drivers_type_net": "网络",
        "hub_drivers_type_netclient": "网络客户端",
        "hub_drivers_type_netdriver": "网络驱动程序",
        "hub_drivers_type_netservice": "网络服务",
        "hub_drivers_type_nettrans": "网络传输",
        "hub_drivers_type_nvmedisk": "NVME 磁盘",
        "hub_drivers_type_ports": "端口",
        "hub_drivers_type_processor": "CPU",
        "hub_drivers_type_scsiadapter": "SCSI 适配器",
        "hub_drivers_type_sensor": "传感器",
        "hub_drivers_type_smartcard": "智能卡",
        "hub_drivers_type_system": "系统内置",
        "hub_drivers_type_unknown": "未知",
        "hub_drivers_type_usb": "USB",
        "hub_drivers_type_volume": "音量",
        "hub_drivers_addtofspe": "是否将此驱动程序添加到 FlysoftPE 内？",
        "hub_drivers_removefromfspe": "是否将此驱动程序从 FlysoftPE 移除？",
        "hub_update_title": "正在下载 FlysoftPE",
        "hub_update_hub_title": "正在下载 FlysoftPE Hub",
        "hub_update_hub_tool_title": "正在下载 FlysoftPE Hub 工具集",
        "hub_update_extract": "正在解包",
        "hub_update_err": "下载因错误中断。要重试吗？",
        "hub_update_mirror": "请选择一个镜像源。",
    },
    "en-us": {
        "com_loading_wait": "Loading...",
        "com_loading_title": "Loading",
        "com_import": "Import",
        "com_explore": "Explore",
        "com_ok": "OK",
        "com_update": "Update",
        "com_next": "Next",
        "com_skip": "Skip",
        "com_continue": "Continue",
        "com_export": "Export",
        "com_cancel": "Cancel",
        "com_complete": "Complete",
        "com_retry": "Retry",
        "com_modify": "Modify",
        "com_apply": "Apply",
        "com_tips": "Tips",
        "com_add": "Add",
        "com_remove": "Remove",
        "com_join": "Join",
        "com_quit": "Quit",
        "com_download": "Download",
        "com_unknown": "Unknown",
        "com_loading": "Loading...",
        "com_empty": "No items here",
        "com_onlype": "This function is only available in FlysoftPE.",
        "ip_welcome": "Welcome to FlysoftPE Import Wizard",
        "ip_import": "Importing FlysoftPE",
        "ip_complete": "Successfully imported FlysoftPE",
        "ip_formaterr": "The ISO Image is not a valid FlysoftPE image.",
        "wiz_welcome": "Welcome to FlysoftPE",
        "wiz_mode": "Select a plan",
        "wiz_mode_ramos": "RAMOS",
        "wiz_mode_pe": "PE",
        "wiz_mode_description_ramos": "This plan is suitable for daily use and has powerful entertainment functions.",
        "wiz_mode_description_pe": "This plan is suitable for maintenance and has many powerful tools.",
        "wiz_device": "Select installation location",
        "wiz_device_usb": "USB",
        "wiz_device_iso": "ISO Image",
        "wiz_install": "Installing FlysoftPE",
        "wiz_complete": "Installed successfully",
        "wiz_anyway": "FlysoftPE is already installed on the local disk. Do you want to continue the installation?",
        "wiz_planerr": "The selected plan does not exist.",
        "wiz_fileerr": "The resource file is missing.",
        "wiz_isoerr": "An error occurred while writing the ISO file.",
        "wiz_usbtip": "Please install Ventoy into USB and click continue.",
        "hub_title": "FlysoftPE",
        "hub_notinstalled": "FlysoftPE boot disk not detected! Please go to the homepage to make a new startup disk.",
        "hub_menu_home": "Home",
        "hub_menu_install": "Install",
        "hub_menu_store": "Store",
        "hub_menu_settings": "Settings",
        "hub_menu_drivers": "Drivers",
        "hub_menu_docs": "Docs",
        "hub_home_write_title": "Install FlysoftPE",
        "hub_home_write_sub": "Please make a new startup disk or insert an existing startup disk",
        "hub_home_write_btn": "Install Now",
        "hub_home_update_title": "FlysoftPE has new updates",
        "hub_home_update_sub": "Update FlysoftPE",
        "hub_home_update_btn": "Update",
        "hub_home_updatehub_title": "FlysoftPE Hub has new updates",
        "hub_home_updatehub_sub": "Please keep the FlysoftPE Hub up to date",
        "hub_home_updatehub_btn": "Update",
        "hub_home_updateusb_title": "The FlysoftPE in your boot disk has new updates",
        "hub_home_updateusb_sub": "Update for a better experience",
        "hub_home_updateusb_btn": "Update",
        "hub_home_offline_title": "You are offline",
        "hub_home_offline_sub": "Please connect to the Internet",
        "hub_home_offline_btn": "Reload",
        "hub_home_loading_title": "Loading...",
        "hub_home_loading_sub": "Please wait...",
        "hub_home_ok_title": "You have installed FlysoftPE",
        "hub_home_ok_3rd_title": "You have installed PE_NAME",
        "hub_home_ok_sub": "Go and install some plugins >>",
        "hub_home_ok_btn": "Go",
        "hub_home_no_title": "Welcome to FlysoftPE",
        "hub_home_no_sub": "To get started, download the resource file first",
        "hub_home_no_btn": "Download Now",
        "hub_store_title": "FlysoftPE Store",
        "hub_store_author": "Author: ",
        "hub_store_time": "Date: ",
        "hub_store_success": "Successful",
        "hub_store_reqerr": "Request Error",
        "hub_store_reqing": "Fetching index",
        "hub_store_downloading": "Downloading...",
        "hub_store_extracting": "Extracting plugin...",
        "hub_store_adding": "Adding to your disk...",
        "hub_store_waiting": "Waiting for your boot disk to be inserted...",
        "hub_store_remove": "Removing ",
        "hub_store_btn1": "Home",
        "hub_store_btn2": "Library",
        "hub_store_btn3": "Installed",
        "hub_store_empty": "Empty",
        "hub_set_title": "FlysoftPE Settings",
        "hub_set_wp": "Wallpaper",
        "hub_set_app": "Appearance",
        "hub_set_app_cmode": "Color Mode",
        "hub_set_app_cmode_theme": "Default",
        "hub_set_app_cmode_light": "Light",
        "hub_set_app_cmode_dark": "Dark",
        "hub_set_app_taskbar": "Taskbar Style",
        "hub_set_app_taskbar_edit": "Edit",
        "hub_set_app_taskbar_remove": "Default",
        "hub_set_disp": "Display",
        "hub_set_disp_bright": "Brightness",
        "hub_set_disp_res": "Resolution",
        "hub_set_disp_res_def": "Auto",
        "hub_set_disp_res_other": "Custom",
        "hub_set_sound": "Sound",
        "hub_set_sound_vol": "Default Volume",
        "hub_set_env": "Environment",
        "hub_set_env_mode": "User Data",
        "hub_set_env_mode_save": "Save to USB",
        "hub_set_env_mode_nosave": "Don't Save",
        "hub_set_insider": "Flysoft Insider",
        "hub_set_insider_join": "Join Flysoft Insider to get the latest features, but it's not so stable.",
        "hub_set_insider_err": "Input the right code",
        "hub_drivers_title": "Drivers",
        "hub_drivers_device": "Driver",
        "hub_drivers_part_amd": "AMD",
        "hub_drivers_part_nvidia": "NVIDIA",
        "hub_drivers_part_intel": "Intel",
        "hub_drivers_part_ms": "Microsoft",
        "hub_drivers_part_qualcomm": "Qualcomm",
        "hub_drivers_part_3dfx": "3DFX",
        "hub_drivers_part_ati": "ATI",
        "hub_drivers_part_google": "Google",
        "hub_drivers_part_apple": "Apple",
        "hub_drivers_part_lsi": "LSI",
        "hub_drivers_part_hp": "HP",
        "hub_drivers_part_hw": "Huawei",
        "hub_drivers_type_1394": "1394",
        "hub_drivers_type_61883": "61883",
        "hub_drivers_type_androidusbdeviceclass": "Android Phone",
        "hub_drivers_type_audioprocessingobject": "Audio Process",
        "hub_drivers_type_avc": "Video Process",
        "hub_drivers_type_barcodescanner": "Barcode Scanner",
        "hub_drivers_type_battery": "Battery",
        "hub_drivers_type_biometric": "Biometric",
        "hub_drivers_type_bluetooth": "Bluetooth",
        "hub_drivers_type_camera": "Camera",
        "hub_drivers_type_cashdrawer": "Cash Drawer",
        "hub_drivers_type_cdrom": "CDROM",
        "hub_drivers_type_computeaccelerator": "Accelerator",
        "hub_drivers_type_computer": "Computer",
        "hub_drivers_type_diskdrive": "Disk",
        "hub_drivers_type_display": "Graphics",
        "hub_drivers_type_dot4": "Dot4",
        "hub_drivers_type_dot4print": "Dot4 Print",
        "hub_drivers_type_extension": "Extension",
        "hub_drivers_type_fdc": "Controller",
        "hub_drivers_type_firmware": "Firmware",
        "hub_drivers_type_floppydisk": "Floppy",
        "hub_drivers_type_image": "Image",
        "hub_drivers_type_keyboard": "Keyboard",
        "hub_drivers_type_fdc": "FDC",
        "hub_drivers_type_modem": "Modem",
        "hub_drivers_type_monitor": "Monitor",
        "hub_drivers_type_media": "Media",
        "hub_drivers_type_mouse": "Mouse",
        "hub_drivers_type_net": "Network",
        "hub_drivers_type_netclient": "Network Client",
        "hub_drivers_type_netdriver": "Network Drivers",
        "hub_drivers_type_netservice": "Network Service",
        "hub_drivers_type_nettrans": "Network Transfer",
        "hub_drivers_type_nvmedisk": "NVME Disk",
        "hub_drivers_type_ports": "Ports",
        "hub_drivers_type_processor": "CPU",
        "hub_drivers_type_scsiadapter": "SCSI Adapter",
        "hub_drivers_type_sensor": "Sensor",
        "hub_drivers_type_smartcard": "Smart Card",
        "hub_drivers_type_system": "System",
        "hub_drivers_type_unknown": "Unknown",
        "hub_drivers_type_usb": "USB",
        "hub_drivers_type_volume": "Volume",
        "hub_drivers_addtofspe": "Add this driver to your FlysoftPE disk?",
        "hub_drivers_removefromfspe": "Remove this driver from your FlysoftPE disk?",
        "hub_update_title": "Downloading FlysoftPE",
        "hub_update_hub_title": "Downloading FlysoftPE Hub",
        "hub_update_hub_tool_title": "Downloading FlysoftPE Hub Toolset",
        "hub_update_extract": "Unpacking FlysoftPE",
        "hub_update_err": "Download is interrupted. Retry?",
        "hub_update_mirror": "Please select a mirror.",
        "hub_update_check": "Checking the fastest mirror source.",
    },
}
var _name = "en-us";
var _3rd;

function reload() {
    if (app.getLocale().indexOf("zh") != -1) {
        _name = "zh-cn";
    } else if (app.getLocale().indexOf("en") != -1) {
        _name = "en-us";
    }
    var dom = document.getElementsByClassName("text");
    for (var i = 0; i < dom.length; i++) {
        dom[i].style.opacity = "1";
        if (dom[i].dataset.text != undefined) {
            if (dom[i].dataset.text.indexOf("{") != -1 && dom[i].dataset.text.indexOf("}") != -1) {
                var langtext = dom[i].dataset.text.replace("{", "").replace("}", "").replace(/\s+/g, "");
                dom[i].innerText = get(langtext);
            }
        }
        if (dom[i].innerText != undefined) {
            if (dom[i].innerText.indexOf("{") != -1 && dom[i].innerText.indexOf("}") != -1) {
                var langtext = dom[i].innerText.replace("{", "").replace("}", "").replace(/\s+/g, "");
                dom[i].dataset.text = dom[i].innerText;
                dom[i].innerText = get(langtext);
            }
        }
    }
    dom = com.selector("img", true);
    for (var i = 0; i < dom.length; i++) {
        dom[i].draggable = false;
    }
}

function get(msg) {
    var data = _data[_name][msg];
    if (data == undefined) {
        data = _data[_name]["com_unknown"];
    }
    if (_3rd != undefined) {
        data = data.replace("FlysoftPE", _3rd);
    }
    com.log(msg + ": " + data);
    return data;
}

function cur() {
    return _name;
}

function set3rd(name) {
    _3rd = name;
}
com.init(function () {
    reload();
});
module.exports = {
    reload: reload,
    get: get,
    cur: cur,
    set3rd: set3rd
}